### ISSUE TITLE
[BUG] 배포 환경에서 발생하는 문제 해결

### ISSUE THREAD

**Issue by sryung1225** [Senity-Waved/Waved_FE#100]
## 🌳 작업 브랜치

`bugfix/#100`

## 🚨 BUG 개요

- 자주 api request가 실패하며, 타임아웃 에러가 지속적으로 발생하였습니다. 원인이나 시점이 파악되지 않아 우선 원인을 찾기 위해 PWA 도입 코드를 제거할 예정입니다.
- 배포 환경에서 현재 페이지에서 동일 페이지로 라우팅 되었을 때 api 호출이 제대로 되지 않아 정상적으로 화면 렌더링이 되지 않는 문제가 발생하였습니다.
- 모바일 결제 시 결제 내역에 같은 결제 내역 데이터가 중복되어 들어가는 걸 확인하였습니다.

## ✅ TODO 및 진행현황

- [x] api request 실패 문제 해결
- [x] api request 실패의 원인 확인을 위한 PWA 제거
- [x] Nav로 이동 시 발생하는 비정상적인 렌더링 문제 해결

## 🚧 BUG 리포트

- PWA 연동을 해제함으로서 api request 실패의 원인이 PWA 임을 좁혔습니다. PWA server workers가 api 호출을 가로채는 과정과 캐싱하는 과정 사이에서 문제가 발생하는 것으로 예상하여 캐시를 초기화하도록 config 옵션을 수정하여 해당 문제는 해결하였습니다. 배포 이후 추가 확인 필요합니다.
- Nav로 페이지 이동 시, 현재 페이지와 동일한 경로는 이동을 할 수 없도록 막았습니다. 또한 로그인하지 않은 유저는 마이 챌린지 이동 시도 자체를 막기 위해 해당 버튼을 disabled 처리하였습니다. 그 처리에 필요한 추가 작업(Footer에 서버사이드 props로 전달 받은 로그인 여부 props로 전달)을 진행하였습니다.
- 모바일 결제 시 결제 정보가 두번 들어가는 문제를 해결하고자 하였으나 클라이언트단에서 해결하기 어려운 문제라 판단되어 백엔드 개발자분들께 공유드렸습니다. (그 과정에서 samesite 속성을 none으로 변경했으나 인과관계가 없다고 판단되어 다시 lax로 변경하였습니다.)
