### ISSUE TITLE
[REFACTOR] 마이챌린지,인증내역 페이지 수정사항 반영 및 리팩토링

### ISSUE THREAD

**Issue by yujin1228** [Senity-Waved/Waved_FE#104]
## 🌳 작업 브랜치

`refactor/#104`

## ✅ TODO 및 진행현황

- [x] 기술 면접 챌린지 > 인증 내역 페이지 : 오늘 인증을 하지 않은 경우 다른 사람 인증 대신에 emptyView 노출
- [x] AB 테스트를 위한 챌린지 스케줄링 2주 -> 1주 변경으로 인한 인증횟수,인증내역스탬프 코드 변경
- [x] 마이챌린지 상태별 emptyView 및 챌린지 둘러보기 컴포넌트 추가
- [x] 사진 확대모달창 크기 변경
- [x] 아이콘 디자인 수정 반영
- [x] 접근성 개선
- [x] EmptyView 공통컴포넌트 수정
