### ISSUE TITLE
[REFACTOR] 깃헙인증제출 후 동작 로직 변경 작업

### ISSUE THREAD

**Issue by yujin1228** [Senity-Waved/Waved_FE#76]
## 🌳 작업 브랜치

`feature/#76`

## 🔨 REFACTORING 개요

깃헙타입(1일1커밋) 챌린지 인증제출 후 동작 로직과 UI변화를 다른타입의 인증제출동작 동일하게 하여 일관성을 유지하도록하는 변경작업입니다.

## ✅ TODO 및 진행현황

- [x] 인증제출 후 페이지이동,스낵바 노출
- [x] 깃헙인증의 경우 다른참여자들의 인증내역을 미제공한다는 점을 안내하는 empty view
- [x] 중복인증 시도 시 404응답 예외 처리
- [x] 인증내역 페이지 디자인 변경 사항 반영
- [x] 인증내역 페이지 날짜 변경 시 기존에 불러온 데이터가 화면에 남아있는 버그 해결
- ~~인증제출 통신실패 시 처리 (다른인증타입도)~~ -> #77 에서 공통으로 해결

## 🚧 REFACTOR 리포트

기존의 동작로직 : 인증제출 후 마이챌린지 페이지에서 진행중인 마이챌린지 데이트를 리패칭하는 방식
변경할 동작로직 : 인증제출 후 인증내역페이지로 이동하며 인증성공 또는 실패 스낵바 노출

+ 깃헙인증 챌린지 유의사항 인증내역페이지에서 안내하기 위한 디자인 변경사항이 있습니다.
