### ISSUE TITLE
[REFACTOR] 디자인 수정사항 반영 및 외부 경로 추가

### ISSUE THREAD

**Issue by eeeyooon** [Senity-Waved/Waved_FE#84]
## 🌳 작업 브랜치

`refactor/#84`

## 🔨 REFACTORING 개요

디자인 수정 사항을 반영하고 api 관련 코드 개선
500 페이지 생성
외부 경로 추가

## ✅ TODO 및 진행현황

- [x] 깃허브 연동관리 input focus일 때 스타일링
- [x] api 관련 코드 개선
- [x] 500 페이지 생성
- [x] 오픈 카톡, 노션 페이지 외부 경로 모두 연결
