### ISSUE TITLE
[REFACTOR] 챌린지 홈 / 상세 구조 수정 및 디자인 수정 반영

### ISSUE THREAD

**Issue by sryung1225** [Senity-Waved/Waved_FE#89]
## 🌳 작업 브랜치

`refactor/#89`

## 🔨 REFACTORING 개요

- 미처 적용하지 못한 에러핸들링을 적용해서 통일성 있는 페이지 완성
- 챌린지 인증 예시 관련 구조 수정

## ✅ TODO 및 진행현황

- [x] 홈 컴포넌트 분류 및 코드 정리
- [X] 챌린지 상세 접근성 보강
- [x] 챌린지 상세 컴포넌트 분류 및 코드 정리
- [x] 챌린지 상세 에러 핸들링 적용
- [x] 챌린지 상세 인증 예시 이미지 확대 기능 추가
- [x] 챌린지 상세 인증 예시 이미지 터치 들뜸 방어
- [x] 챌린지 신청 취소 리로드 방식 변경
